//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetflixApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MyTable
    {
        public int Id { get; set; }
        public string Generes { get; set; }
        public string Title { get; set; }
        public string Language { get; set; }
        public string Starring { get; set; }
        public System.DateTime Released_Date { get; set; }
        public int Rating { get; set; }
    }
}
